# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Phantato
auth: ZHTan
email: phantatojames@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I’m a college student majoring in Information and Computing science and this is a blog recording my leetcode solutions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "Phantato.github.io/leetcodeSolution" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  Phantato

# Exerpt Separator
excerpt_separator: <!--exerpt-->

# Build >ettings
markdown: kramdown
